create table if not exists users (
                                     id bigint generated by default as identity primary key,
                                     username varchar(255) not null unique,
    password_hash varchar(255) not null,
    api_token varchar(64) unique,
    token_created_at timestamp
    );

create table if not exists files (
                                     id uuid primary key,
                                     original_name varchar(1024) not null,
    content_type varchar(255),
    size_bytes bigint not null,
    storage_path varchar(2048) not null,
    download_token varchar(64) not null unique,
    created_at timestamp not null default current_timestamp,
    last_download_at timestamp null,
    download_count bigint not null default 0
    );

create index if not exists files_last_download_idx on files (last_download_at);
